import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stringify as stringifyYaml } from "yaml";
import type { ProjectData } from "@crisiskit/core";
import { CRISISKIT_REPO_URL } from "@crisiskit/core";
import { HA_QUICK_LINK_PAGES } from "./nav-items.js";

export interface RenderHomeAssistantResult {
  files: string[];
}

const STRINGS = {
  de: {
    monitoredDevices: "Überwachte Geräte",
    notfallmodus: "Notfallmodus (CrisisKit)",
    emergencyMode: "Notfallmodus",
    staticNote: "Statische Seiten aus CrisisKit. Ersetzt keine amtlichen Warnungen.",
    iframeTitle: "Notfallmappe",
    packageReview: "Generated by CrisisKit — review before enabling in production",
  },
  en: {
    monitoredDevices: "Monitored devices",
    notfallmodus: "Emergency mode (CrisisKit)",
    emergencyMode: "Emergency mode",
    staticNote: "Static pages from CrisisKit. Does not replace official warnings.",
    iframeTitle: "Emergency kit",
    packageReview: "Generated by CrisisKit — review before enabling in production",
  },
} as const;

function stringsFor(data: ProjectData) {
  return data.config.project.language === "en" ? STRINGS.en : STRINGS.de;
}

function wwwBasePath(subdirectory: string): string {
  return `/local/${subdirectory.replace(/^\/+|\/+$/g, "")}`;
}

function buildQuickLinkCards(subdirectory: string) {
  const base = wwwBasePath(subdirectory);

  return {
    type: "horizontal-stack",
    cards: HA_QUICK_LINK_PAGES.map((page) => ({
      type: "button",
      name: page.name,
      icon: "mdi:open-in-new",
      tap_action: {
        action: "url",
        url_path: `${base}/${page.path}`,
      },
    })),
  };
}

function hasPackageContent(data: ProjectData): boolean {
  const ha = data.homeAssistant!;
  return ha.automations.length > 0 || ha.entities.length > 0;
}

function buildLovelaceDashboard(data: ProjectData) {
  const ha = data.homeAssistant!;
  const base = wwwBasePath(ha.www.subdirectory);
  const t = stringsFor(data);

  const cards: Record<string, unknown>[] = [
    {
      type: "markdown",
      content: [
        `**${data.config.project.name}**`,
        "",
        data.config.disclaimer.text,
        "",
        t.staticNote,
      ].join("\n"),
    },
    buildQuickLinkCards(ha.www.subdirectory),
    {
      type: "iframe",
      url: `${base}/index.html`,
      aspect_ratio: "50%",
      title: t.iframeTitle,
    },
  ];

  if (hasPackageContent(data)) {
    cards.push({
      type: "entities",
      title: t.emergencyMode,
      show_header_toggle: false,
      entities: [
        {
          entity: "input_boolean.crisiskit_notfallmodus",
          name: t.notfallmodus,
        },
      ],
    });
  }

  if (ha.entities.length > 0) {
    cards.push({
      type: "entities",
      title: t.monitoredDevices,
      show_header_toggle: false,
      entities: ha.entities.map((entity) => ({
        entity: entity.entity_id,
        name: entity.label,
        ...(entity.icon ? { icon: entity.icon } : {}),
      })),
    });
  }

  return {
    title: ha.dashboard.title,
    views: [
      {
        title: ha.dashboard.title,
        path: ha.dashboard.path,
        icon: ha.dashboard.icon,
        cards,
      },
    ],
  };
}

function buildPackageYaml(data: ProjectData) {
  const ha = data.homeAssistant!;
  const base = wwwBasePath(ha.www.subdirectory);
  const packageDoc: Record<string, unknown> = {};

  if (hasPackageContent(data)) {
    packageDoc.input_boolean = {
      crisiskit_notfallmodus: {
        name: stringsFor(data).notfallmodus,
        icon: "mdi:shield-alert",
      },
    };
  }

  if (ha.automations.length > 0) {
    packageDoc.automation = ha.automations
      .filter((automation) => automation.enabled)
      .map((automation) => {
        const actions: unknown[] = [];

        if (automation.notify === "persistent_notification") {
          actions.push({
            service: "persistent_notification.create",
            data: {
              title: data.config.project.name,
              message:
                automation.message ??
                `Ereignis erkannt (${automation.trigger_entity}). Notfallmappe: ${base}/power-outage.html`,
            },
          });
        }

        if (automation.enable_notfallmodus) {
          actions.push({
            service: "input_boolean.turn_on",
            target: {
              entity_id: "input_boolean.crisiskit_notfallmodus",
            },
          });
        }

        const trigger: Record<string, string> = {
          platform: "state",
          entity_id: automation.trigger_entity,
          to: automation.trigger_to,
        };
        if (automation.trigger_from) {
          trigger.from = automation.trigger_from;
        }

        return {
          id: `crisiskit_${automation.id}`,
          alias: automation.alias,
          description: stringsFor(data).packageReview,
          trigger: [trigger],
          condition: [],
          action: actions,
          mode: "single",
        };
      });
  }

  return packageDoc;
}

function buildInstallMarkdown(data: ProjectData): string {
  const ha = data.homeAssistant!;
  const subdir = ha.www.subdirectory.replace(/^\/+|\/+$/g, "");
  const projectName = data.config.project.name;
  const de = data.config.project.language !== "en";

  return `# Home Assistant Integration — ${projectName}

Generated by [CrisisKit](${CRISISKIT_REPO_URL}). Compatible with [Home Assistant](https://www.home-assistant.io/) local-first setup.

## 1. Copy static files

Copy the **contents** of your CrisisKit \`dist/\` folder (HTML, assets, pdf) into Home Assistant:

\`\`\`
/config/www/${subdir}/
\`\`\`

Home Assistant serves files from \`/config/www/\` at \`/local/\`.

Example:

\`\`\`bash
scp -r dist/* user@homeassistant:/config/www/${subdir}/
\`\`\`

Verify: open \`${wwwBasePath(subdir)}/index.html\` in your browser while logged into Home Assistant.

## 2. Import Lovelace dashboard

File: \`lovelace-dashboard.yaml\`

In Home Assistant:

1. Settings → Dashboards → Add dashboard
2. Enable YAML / raw configuration (or paste into a new view via raw config editor)
3. Paste the contents of \`lovelace-dashboard.yaml\`

Adjust entity IDs in the dashboard if your sensors differ.

## 3. Optional: load package

File: \`package.yaml\`

Copy \`package.yaml\` from this folder to:

\`\`\`
/config/packages/crisiskit.yaml
\`\`\`

Ensure packages are enabled in \`configuration.yaml\`:

\`\`\`yaml
homeassistant:
  packages: !include_dir_named packages
\`\`\`

Reload packages: **Developer Tools → YAML → Reload Packages**.

**Review automations before enabling.** CrisisKit generates helpers and notification automations only — no remote access, no cloud.

## 4. Privacy

Your ${de ? "Notfallmappe" : "emergency kit"} may contain private phone numbers and medical notes. Home Assistant stays local, but anyone with dashboard access can see embedded pages and configured entities.

## Disclaimer

CrisisKit does not replace official warnings (NINA), emergency services, or medical advice.
`;
}

export function renderHomeAssistant(
  data: ProjectData,
  outputDir: string,
): RenderHomeAssistantResult | null {
  if (!data.homeAssistant?.enabled) {
    return null;
  }

  const haDir = join(outputDir, "home-assistant");
  mkdirSync(haDir, { recursive: true });

  const files: string[] = [];

  const lovelacePath = join(haDir, "lovelace-dashboard.yaml");
  writeFileSync(
    lovelacePath,
    stringifyYaml(buildLovelaceDashboard(data), { lineWidth: 0 }),
    "utf-8",
  );
  files.push("home-assistant/lovelace-dashboard.yaml");

  const packageDoc = buildPackageYaml(data);
  if (Object.keys(packageDoc).length > 0) {
    const packagePath = join(haDir, "package.yaml");
    writeFileSync(packagePath, stringifyYaml(packageDoc, { lineWidth: 0 }), "utf-8");
    files.push("home-assistant/package.yaml");
  }

  const installPath = join(haDir, "INSTALL.md");
  writeFileSync(installPath, buildInstallMarkdown(data), "utf-8");
  files.push("home-assistant/INSTALL.md");

  return { files };
}
